# Para testar as URIs, utilizar a extensão do vscode abaixo:

# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.1
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# ApiService ------------------------------------------
###
GET http://localhost:8080/escalacao/api
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/time-da-data/21-04-1987
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/integrante-mais-usado/01-11-2022/20-11-2024
Accept: application/json
Content-Type:application/json

{

}
# TIME ----------------
###
GET http://localhost:8080/escalacao/api/time/1
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/time/listar
Accept: application/json
Content-Type:application/json
###
POST http://localhost:8080/escalacao/api/time/salvar
Accept: application/json
Content-Type:application/json

{
    "descricao": "time salvar",
    "data": [
      2024,
      11,
      20
    ],
    "franquia": null,
    "composicaoTime": []
}


# FRANQUIA ------------
###
GET http://localhost:8080/escalacao/api/franquia/12
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/franquia/listar
Accept: application/json
Content-Type:application/json
###
POST http://localhost:8080/escalacao/api/franquia/salvar
Accept: application/json
Content-Type:application/json

{
    "nome": "franquia request"
}

# FUNCAO ------------
###
GET http://localhost:8080/escalacao/api/funcao/14
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/funcao/listar
Accept: application/json
Content-Type:application/json
###
POST http://localhost:8080/escalacao/api/funcao/salvar
Accept: application/json
Content-Type:application/json

{
    "nome": "funcao request"
}

# INTEGRANTE ----------
###
GET http://localhost:8080/escalacao/api/integrante/14
Accept: application/json
Content-Type:application/json
###
GET http://localhost:8080/escalacao/api/integrante/listar
Accept: application/json
Content-Type:application/json
###
POST http://localhost:8080/escalacao/api/integrante/salvar
Accept: application/json
Content-Type:application/json

{
    "nome": "integrante request"
}